### ISSUE TITLE
Upcoming Events consistently out of date

### ISSUE THREAD

**Issue by phall-brown** [brown-ccv/ccv-website-hugo#114]
The "Upcoming Events" on the home page regularly features events that are several weeks old. Is it possible to get the feature to flush out old events automatically on a regular basis? If not, maybe we should just nix this section entirely (or replace it with the calendar view from the events.brown.edu/ccv).

**Comment by fernandogelin** [comment]
addressed in ba0d681ef5f86b14b295e1254816d438877558e6
