### ISSUE TITLE
Apps/Workshops: Separate linking of title from github

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/ccv-website-hugo#120]
The title should link out to the site_url (if available), the github icon should only exist if a repo_url provided (in some cases it may be private, so not part of the ready.yaml).  If there is a repo_url and no site_url, the title should link to the repo.

**Comment by TiffL** [comment]
@mcmcgrath13 If there is no repo_url and no site_url, should the app/workshop still be included, just with the title not a link?

**Comment by mcmcgrath13** [comment]
I'm tempted to say there has to be at least one URL, without that the card doesn't do much... @brown-ccv/web-admin what do you think?

**Comment by mirestrepo** [comment]
hmmm - but there is always a repo because the ready.yml is inside the repo. Maybe repo_url should default to the repo being queried or be mandatory.

**Comment by mcmcgrath13** [comment]
But in some cases the repo is private, so we don't want to link to it.  We
could always check the private/public status, then default it if public?

**Comment by mirestrepo** [comment]
hmmmm. maybe we change the icon for private githubs to a lock, but still link to it?

**Comment by mcmcgrath13** [comment]
I think that's more confusing since it goes to a 404 not found page if you
don't have access.  I vote just leave off the github icon and only link to
the site_url.

**Comment by mirestrepo** [comment]
Sounds good to me.

**Comment by mirestrepo** [comment]
And so if private, there must be project_url.

**Comment by fernandogelin** [comment]
closing this as workshops/software are moving out of hugo
