### ISSUE TITLE
Consulting Section suggestions

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#130]
1. Combine HPC and Visualization into Advanced Research Computing. I'm not sure whether the name "Advanced Research Computing" is dead.  Maybe just a one page on consulting.  

2. Remove Discourse from this section - maybe have a "getting help" section?

**Comment by mirestrepo** [comment]
I totally agree here. I'm happy to take on combining that content and sending it out for revision

**Comment by mirestrepo** [comment]
@paulstey what do yo think about Helen's suggestions?

**Comment by mirestrepo** [comment]
Maybe the Cards are HPC, Data Science, Visualization, Software Engineering and Computational Biology - but if you click on details they all go to the same (ARC) Consulting summary page. How do you feel about that?

**Comment by paulstey** [comment]
I like the idea of combining them.

**Comment by fernandogelin** [comment]
@mirestrepo @paulstey I'll address this issue, and send you a PR for review.
