### ISSUE TITLE
Edit Description of Oscar 

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#131]
1. Should sound cooler and have pictures.  & be more welcoming
2. Info is out of date
3. Remove anthropomorphism from the description.
4. Add link to Oscar documentation
5. Add support@ccv.brown.edu

**Comment by paulstey** [comment]
@hkershaw-brown : Regarding (1.), would you mind taking a crack at some cooler language? Also, do we have pictures of the machine room?

**Comment by hkershaw-brown** [comment]
oh yeah I assigned my self to this issue.  I think.

**Comment by fernandogelin** [comment]
@hkershaw-brown @paulstey can you reassign this to someone? I'm not sure who the right person is.

**Comment by fernandogelin** [comment]
@hkershaw-brown @paulstey has there been any progress on this? If you give me the new text I can update the website. 
Thanks

**Comment by hkershaw-brown** [comment]
hi @fernandogelin  I don't have the details about Oscar.
