### ISSUE TITLE
terms and conditions page

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#136]
There is a terms and conditions page that you can reach by searching for it but I don't think is linked from anywhere.  
Are these the correct terms and conditions?

**Comment by fernandogelin** [comment]
There used to be a link for this in the old form to create an account. @hkershaw-brown Where's the best place for this? In the oscar page? 
I'll assign to @mttunca to review the content.

@mttunca can you review: https://ccv.brown.edu/services/infrastructure/terms-and-conditions/

**Comment by hkershaw-brown** [comment]
There's a different sent of conditions in the Oscar docs:
https://docs.ccv.brown.edu/oscar/getting-help/ccv-user-policies

**Comment by mirestrepo** [comment]
For JupyterHub, the terms and conditions are in the user-manual(Gitbook). Is than maybe where we should put it for Oscar as well? It's probably a good idea to be consistent across different compute resources. @mttunca Should we also do the same for stronghold?

**Comment by mcmcgrath13** [comment]
There's also the citing ccv in the about page, which seems somewhat related to terms and conditions, since if you use our infrastructure/services, it should be a term/condition to cite that?

**Comment by fernandogelin** [comment]
@paulstey @mttunca can you look into this?

**Comment by fernandogelin** [comment]
@paulstey @mttunca any update on this?

**Comment by fernandogelin** [comment]
@paulstey @mttunca any update on this?

**Comment by fernandogelin** [comment]
@paulstey @mttunca any update on this?

**Comment by ljwolfe1** [comment]
All T&Cs should be removed from the site per OVPR. They are already covered under IT policies that are currently published at: https://it.brown.edu/computing-policies. This is for reference only and should not be referenced from the CCV site. There is an effort underway to publish all Brown policies in one place and that will be the final resting place for these IT policies as well. https://ccv.brown.edu/services/infrastructure/terms-and-conditions/ should be deleted and not referenced on the site.

**Comment by fernandogelin** [comment]
@ljwolfe1 perfect! thank you for your input. I'll remove that ASAP.
