### ISSUE TITLE
Add XSEDE info

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#137]

**Comment by paulstey** [comment]
@fernandogelin: What do you think about adding an "Additional Resources" section, or something similar in a future release?

**Comment by fernandogelin** [comment]
@hkershaw-brown Do you have the XSEDE info? If you give me what you have I can work on adding to the website.

**Comment by hkershaw-brown** [comment]
Here you go:

[XSEDE](https://www.xsede.org/) is an NSF-funded, nationwide collection of supercomputing systems that are available to researchers through merit-based allocations.  The resources are free, but the application process is competitive.  CCV participates in the Campus Champions program and has a small pool of compute time available for Brown researchers to try out XSEDE resources.   This is a great way to test your code on XSEDE systems before getting your own allocation. 

Deadlines for research allocations are quarterly:

SUBMISSION PERIOD | MEETING DATE | USERS NOTIFIED | ALLOCATION BEGIN DATE
-- | -- | -- | --
Dec 15 thru Jan 15 | Early March | March 15 | April 1
Mar 15 thru Apr 15 | Early June | June 15 | Jul 1
Jun 15 thru Jul 15 | Late August/Early September | September 15 | Oct 1
Sep 15 thru Oct 15 | Early December | December 15 | Jan 1

If you would like help getting started with XSEDE , please contact support@ccv.brown.edu with a description of your project and which XSEDE systems you would like to access. We can also assist you in preparing the 'Code Performance & Resource Costs' section of your research allocation proposal.

**Comment by hkershaw-brown** [comment]
@fernandogelin see above comment for XSEDE info

**Comment by fernandogelin** [comment]
Thank you @hkershaw-brown !!!
