### ISSUE TITLE
 imposter website giving out false information

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#138]
I am led to believe that CCV is the one true place for research computing.

https://it.brown.edu/services-research  needs to be removed.

It is full of broken links that take users to the 'go home dog' page, e.g. this page: https://it.brown.edu/services/type/research-software has a broken link https://www.ccv.brown.edu/software, this page: https://it.brown.edu/services/type/research-computing-support has a broken link for requesting an Oscar account. multiple entries on this page https://it.brown.edu/taxonomy/term/455.  The side bar on these pages is also all cis (help@brown.edu, etc).

**Comment by mirestrepo** [comment]
I submitted a ticket-160561. Let's hope it doesn't get assigned to ccv ;)

**Comment by hkershaw-brown** [comment]
Closing this issue since it is not under the ccv website. 
Note it did get assigned to CCV: ticket 160561
