### ISSUE TITLE
Update README with procedure, labels, processes

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/ccv-website-hugo#144]
As we figure this out, need to make sure README has proper documentation.  Perhaps break it out into a `CONTRIBUTING.md`.  Add issue and PR templates to make process integrated with technology.

- [x] README.md
- [x] CONTRIBUTING.md
- [x] Issue template
- [x] PR template

**Comment by mcmcgrath13** [comment]
@fernandogelin  does #157 close this?

**Comment by fernandogelin** [comment]
after it gets reviewed and approved.
