### ISSUE TITLE
[CONTENT] jupyter hub link has changed

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-hugo#152]
**Describe why you'd like the content to be updated**
Request form for JupyterHub needs to be updated. Link has changed

**Enter the part that you want to replace**
I can do this on a PR, if assigned to me ;)

**Enter the new content**
I can do this on a PR, if assigned to me ;)

**Comment by paulstey** [comment]
@mirestrepo : Are you still okay fixing this? Or can I take a crack at it?

**Comment by mirestrepo** [comment]
My plan is now to keep the link the way it is and add script to the google form to create the ticket. I prefer the google form to the Qualtrics because we can more easily keep track and share the results.....

**Comment by mirestrepo** [comment]
But we could probably update the description a bit... I know TJ had changed few sentences in here https://docs.google.com/document/d/1_1X7n94A1YBBkUMjTG0NDAiPXQStWw54BT5Cjv9JcII/edit

And I would be more than happy to pass this issue to you!

Is there any other info that you think we should include?

**Comment by fernandogelin** [comment]
@mirestrepo were you able to create the Google Script? What's the status of this issue?

**Comment by fernandogelin** [comment]
hi @mirestrepo what's the status of this. Do you want me to take care of this? If so, what needs to be done?

**Comment by mirestrepo** [comment]
@fernandogelin I don't see the link in the website to request a hub, anymore...?
 What needs to be done is the google script for Deskpro. I would be more than relieve if someone take it from me

**Comment by mirestrepo** [comment]
And the description needs to be changed to:

```
JupyterHub provides a convenient, cloud-hosted way to serve Jupyter Notebooks for multiple users. Notebooks are launched within a pre-configured computing environment;users do not need to instal any software packages. This set-up free environment is ideal for courses and workshops where instructors intend for students to begin coding with minimal obstacles.. 

If you are an instructor, CCV can provide access to JupyterHub for your class or workshop, and Digital Learning and Design (DLD) can assist with integrating computational assignments into curricula. The implementation is supported by Brown CIS; please follow the links below to request an instance for your class or search the documentation.
```

I also see that the buttons are not showing up anymore for requesting the service

**Comment by fernandogelin** [comment]
@mirestrepo the form is still that Google Doc? And it should send a ticket to jupyterhub-help@brown.edu on submit?

**Comment by mirestrepo** [comment]
@fernandogelin - Correct! The form is [here](https://docs.google.com/forms/d/1B7nSLcupLWGWLWvIoQjeygJpPVd4w9KonGN3vclHQdM/edit)

**Comment by paulstey** [comment]
Are we okay to close this one now? I think it's been resolved.

@mirestrepo: Can you please take a look?

**Comment by mirestrepo** [comment]
The button is fixed... @fernandogelin just checking... is the form generating tickets? Are you helping me with that? or am I supposed to do that....?

**Comment by fernandogelin** [comment]
@mirestrepo I'm planning on doing it, but haven't had time yet.
