### ISSUE TITLE
[BUG] Don't show archived projects

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/ccv-website-hugo#155]
**Describe the bug**
Archived repos should not be pulled for the software and workshop pages.

**Expected behavior**
No archived repos shows as software projects, apps, or workshops

n/a

**Additional context**
brown-ccv/pubmedminer is archived, but has a ready.yaml leftover from it's prior life - this **SHOULD NOT** be on brown-ccv's website

**Comment by mcmcgrath13** [comment]
I removed the ready.yaml from the problem repo, but we should include this for the next update to that page

**Comment by fernandogelin** [comment]
closing this as workshops/software are moving out of hugo
