### ISSUE TITLE
[DATA UPDATE] - Add Kuba to intern section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#159]
**Describe why you'd like the content to be updated**
We should add Kuba (Mete's student) to the intern section

**Enter the new content**
We need a main picture and a hover pic for Kuba 

**Additional context**
@mttunca and @ashleysyg: Can the two of you work to get a couple of pics of Kuba?

**Comment by fernandogelin** [comment]
@paulstey I'll close this and reopen with the correct template.
