### ISSUE TITLE
[FEATURE] Add CCV-Con section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#163]
**Is your feature request related to a problem? Please describe.**
Could we please add a section for CCV-Con? And in particular, can we add the slides from CCV-Con 2019? They are in the ARC-CCV shared Google Drive. We still need Mete's day, though. I'll get those.

**Describe the solution you'd like**
Adding a section that houses slides from CCV-Con 2019

**Describe alternatives you've considered**
NA

**Additional context**
You're awesome!! Thank you so much!!!

**Comment by fernandogelin** [comment]
@mirestrepo suggested to have a section under workshops(?) with a card linking to GitHub repo with slides.

**Comment by mcmcgrath13** [comment]
Create a repo with a `ready.yaml` have a folder for each year and in that folder have a `README` that links to the appropriate google drive

**Comment by fernandogelin** [comment]
completed
