### ISSUE TITLE
[FEATURE] Link to YURT group demo form in the front page

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/ccv-website-hugo#165]
**Is your feature request related to a problem? Please describe.**
I receive emails requesting a YURT demo. I send the link to the google form, but I think it is too hidden and any user could struggle to find it. We could just say "Go to the ccv main page and look for the link Request_YURT_demo link"

**Describe the solution you'd like**
Users can easily request a demo just by entering to the ccv main webpage

**Comment by ljwolfe1** [comment]
Can this be closed?

**Comment by paulstey** [comment]
@ljwolfe1: Yes, agreed. I'll close it for now.
