### ISSUE TITLE
rates on data science consulting

### ISSUE THREAD

**Issue by azsom** [brown-ccv/ccv-website-hugo#17]
numbers tbd, but I'll add them soon.

**Comment by fernandogelin** [comment]
@paulstey I remember this was discussed in one of our meetings. I can't remember why we decided not to add those rates. Should they be included?

**Comment by azsom** [comment]
Yes. :) @paulstey , what do you think about the text below?

There are three opportunities how Brown affiliates can work with us.

1) We are happy to perform short well-defined exploratory analyses to support grant preparation. The expectation is that one or more data scientists from the team would become part of the research project if the grant is successful and resources are allocated to support the data scientist's continued work on the project.

2) We are also available for consulting services for Brown-affiliates. Consulting costs $100/hour or $200/hour if it is urgent. Consulting means that we meet with the collaborator once or twice a week for an hour and we advise them on best practices and give suggestions on what to try next. Most of the coding work is done by the collaborator.

3) It is also possible to "buy out" a data scientist's time if the collaborator requests that the data scientist does the coding work. 20% to maximum 60% FTE of a data scientist's time needs to be supported from a grant in this case for a duration agreed upon beforehand.

We are also happy to work with companies in the area. If you are interested in working with us, please reach out to cis-datascience@brown.edu.

**Comment by fernandogelin** [comment]
@azsom @paulstey I think topic 1 is already in the ARC page. Point 2 should go with the other rates, if we decide to have them on the website. Point 3 isn't general to all groups, and should be considered carefully. The work with companies should be expanded upon, and should maybe go in the ARC page.

**Comment by fernandogelin** [comment]
We should maybe also point out that we don't only work with Brown, but also other universities in the area.

**Comment by azsom** [comment]
Oh, we do? :)

**Comment by azsom** [comment]
We could also say that there are a couple of opportunities at Brown to secure a small grant to start collaborating with us. So it's OK if someone doesn't have funds readily available.
