### ISSUE TITLE
[FEATURE] Refactor Calendar 

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-hugo#177]
**Is your feature request related to a problem? Please describe.**
The Google Calendar is ugly and doesn't show events that are created directly in the events@brown site

**Describe the solution you'd like**
Look into the possibility of using LiveWhale API to display events on the website.

**Comment by ljwolfe1** [comment]
Who needs to comment on details of this request?

**Comment by fernandogelin** [comment]
@ljwolfe1 That's on my plate, I need to look into the possibility of using the LiveWhale API to get the data from events@brown. I'm not sure who's in charge of LiveWhale.

**Comment by fernandogelin** [comment]
complete
