### ISSUE TITLE
[BUG] HPC Position has semi-dead link

### ISSUE THREAD

**Issue by mcmcgrath13** [brown-ccv/ccv-website-hugo#188]
**Describe the bug**
Senior/Research Software Engineer position's link is semi-dead

**Expected behavior**
Link should be not dead, or the posting should be removed

**Screenshots**

**Additional context**
@hkershaw-brown should this be removed? or is there a new link?

**Comment by hkershaw-brown** [comment]
This post has been filled, but there is a new posting:

Research Software Engineer

https://brown.wd5.myworkdayjobs.com/en-US/staff-careers-brown/job/180-George-Street/Research-Software-Engineer_REQ164152

**Comment by mcmcgrath13** [comment]
Just started a PR to remove the old posting.  It looks like the new one is already there.
