### ISSUE TITLE
[CONTENT] Facilities Statement in its own Sub-section

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#200]
**Describe why you'd like the content to be updated**
I think the Facilities Statement should be its own stand-alone subsection on our _About_ page. Right now, it's a bit tucked away under _How to Cite CCV_. I think a new subsection that is strictly the Facilities Statement would help this be more obvious to users.

**Enter the part that you want to replace**
Facilities Statement on the _About_ page

**Comment by ljwolfe1** [comment]
This was recommended by Thomas Serre. Is this difficult to implement? If not, can we move forward with this?

**Comment by fernandogelin** [comment]
@ljwolfe1 We are working on solving all issues, including this one.

**Comment by paulstey** [comment]
PR 207 will fix this when merged to production.

**Comment by paulstey** [comment]
We can close this, since PR 207 has been merged.
