### ISSUE TITLE
[CONTENT] Disable buttons on the YURT Web Page and add message

### ISSUE THREAD

**Issue by kmilo9999** [brown-ccv/ccv-website-hugo#213]
**Describe why you'd like the content to be updated**
Due to the state of emergency in the country, YURT demos wont be authorized until further notice. This has to be explained in the ccv YURT web page

**Enter the part that you want to replace**
On the CCV YURT web page, disable the buttons:
"Book your visit here"  and " Request a Group Demo"

**Enter the new content**
Add a message on top of the "Regular Open House" subtitle:

"For the health and safety of the community, we will no offer demos until further notice.  We continue to monitor the coronavirus situation closely and we are taking action based on guidance from public health experts. Please stay safe"

**Comment by paulstey** [comment]
Are we all set with this, @fernandogelin and @kmilo9999? I think PR 218 resolved this, no?
