### ISSUE TITLE
[BUG] Search is showing ads

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#220]
**Describe the bug**
I'm not sure if this has already been reported, but it seems our Google custom search is showing ads. Can this be turned off? 

If we can't turn off that functionality, I really think we ought to consider alternatives. 

As always, thank you!!

**Comment by fernandogelin** [comment]
@paulstey It looks like we can turn that off but need to do the following: If your organization is already are registered with Google for Education, have your organization add the email address that is the owner of the Custom Search Engine or a verified administrator of the Custom Search Engine as a Super Admin of the domain.

Do you know who controls the Google for Education account? Can you ask them to add one of us as Super Admin?

https://support.google.com/customsearch/answer/4542102?hl=en

**Comment by ljwolfe1** [comment]
I will look into this. That area falls under Don Rogers/Chris Grossi's area.
