### ISSUE TITLE
[CONTENT] Typos in Cave and YURT descriptions

### ISSUE THREAD

**Issue by mirestrepo** [brown-ccv/ccv-website-hugo#236]
**Describe why you'd like the content to be updated**
Typos in YURT and CAVE description

**Enter the part that you want to replace**
Reported by Thomas, need to check

**Comment by paulstey** [comment]
There seems to be an unnecessary `"images"` in the Cave page. And the Yurt pages seems to be missing the word `"longer"` at the bottom. I'll fix this.

**Comment by paulstey** [comment]
This issue is fixed by PR `238`.

**Comment by paulstey** [comment]
As `#238` has now been merged, I'm going to close this issue.
