### ISSUE TITLE
COVID-19 HPC Resources 

### ISSUE THREAD

**Issue by ljwolfe1** [brown-ccv/ccv-website-hugo#239]
**Describe why you'd like the content to be updated**
Append the description of the HPC resources paragraph with eligibility requirements.

**Enter the part that you want to replace**
Either write here the piece of content to be replaced or enter the line numbers. 

**Enter the new content**
Any Brown faculty member whose salary is paid by Brown or whose research is administered through Brown is eligible to be a Principal Investigator. Brown faculty employed by affiliated institutions, or Brown faculty whose research is administered through affiliated institutions, may be included as co-PIs on the research team.

**Additional context**
# Describe the c

**Comment by paulstey** [comment]
I'll take this one! Thanks, @ljwolfe1!!
