### ISSUE TITLE
COVID-19 Index does not work

### ISSUE THREAD

**Issue by ljwolfe1** [brown-ccv/ccv-website-hugo#240]
**Describe the bug**
When you click on one of the entries in the COVID-19 index you do not move to the section of the page with that information.

**Expected behavior**
Clicking on one of those entries will position the user to that point in the page.

**Screenshots**

**Additional context**

**Comment by ljwolfe1** [comment]
![COVID Index](https://user-images.githubusercontent.com/48321145/78904047-00ee3080-7a4a-11ea-9b6c-11fb2f9e2d9c.GIF)

**Comment by ljwolfe1** [comment]
Those entries do not position the user to the right place on the page.

**Comment by paulstey** [comment]
Thanks for the quick fix, @mcmcgrath13 and @fernandogelin!!!
