### ISSUE TITLE
[BUG] google form opens in the calendar

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#253]
**Describe the bug**
Clicking on the google form link in the calendar opens the google form in the calendar frame, which you then cannot scroll down to submit the form.  
There seems to be no way to go back to the calendar.

Side note: the 'More info' appears to have a strikethrough ~~More info~~

**Expected behavior**
I don't think the google form should open up in the calendar.  I think clicking on the event should open a new page to events.ccv.brown.edu.  

**Screenshots**
Added 3 screenshots to tell the story.  

<img width="380" alt="Screen Shot 2020-05-06 at 5 18 23 PM" src="https://user-images.githubusercontent.com/20047007/81230144-f4181a80-8fbe-11ea-9995-363cfc409782.png">
<img width="544" alt="Screen Shot 2020-05-06 at 5 18 06 PM" src="https://user-images.githubusercontent.com/20047007/81230167-f8dcce80-8fbe-11ea-9e61-8a6bd1e4b65f.png">
<img width="1207" alt="Screen Shot 2020-05-06 at 5 23 41 PM" src="https://user-images.githubusercontent.com/20047007/81230178-fda18280-8fbe-11ea-9c51-a6a7182608c4.png">

**Additional context**

**Comment by fernandogelin** [comment]
@hkershaw-brown good catch! A quick fix is to add `target="_blank"` to the `<a>` tag in the event description. I did that for `getting started on oscar` and `using matlab`.  
I'll look into add some js that does that for all links in the iframe.

**Comment by fernandogelin** [comment]
also, @hkershaw-brown which browser are you seeing the strikethrough?

**Comment by hkershaw-brown** [comment]
Chrome, but I realized it is because of the zooming out I did to show the
screen shot.


Helen Kershaw
Lead Research Software Engineer
Center for Computation and Visualization
Brown University
XSEDE Campus Champion
http://www.ccv.brown.edu

**Comment by fernandogelin** [comment]
I added a fix to the calendar that will add `target=_blank` to `<a>` in the description that are missing a target.
