### ISSUE TITLE
[CONTENT] Remove references to the YURT

### ISSUE THREAD

**Issue by ljwolfe1** [brown-ccv/ccv-website-hugo#279]
**Describe why you'd like the content to be updated**
Remove any references to the YURT on the CCV site

**Enter the part that you want to replace**
https://ccv.brown.edu/services/infrastructure/yurt/

**Enter the new content**
Remove

**Additional context**
I did not exhaustively go through the site, but other references to the YURT should also be removed.

**Comment by paulstey** [comment]
I'll take this one!

**Comment by paulstey** [comment]
I think this was resolved by `#280`. Closing for now.
