### ISSUE TITLE
180 George Street Address

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#30]
Two addresses:
Address of building
PO Box address for correspondence  ( I think this is PO Box 1841)

**Comment by mcmcgrath13** [comment]
@hkershaw-brown  Where should these be listed? Is the address wrong somewhere?

**Comment by hkershaw-brown** [comment]
I think the address is just missing.

Postal - so people can send us Christmas presents
Building - so people can find us

Maybe it should go in the footer?
