### ISSUE TITLE
[FEATURE] Add banner linking to status page

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#301]
It would be good if we had a banner on the front page that links to the status page. We can use this banner when there are service disruptions to direct users to the status page and the updates that appear there.

**Comment by paulstey** [comment]
I'll work on this!

**Comment by fernandogelin** [comment]
@paulstey do you really want to work on this? I'm thinking we need to create a route in the ember app with the banner and add to the hugo site as an iframe.

**Comment by paulstey** [comment]
Thanks, @fernandogelin!! I did not realize that.
