### ISSUE TITLE
rates page is incorrect

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#31]
https://ccv.brown.edu//services/rates/

shows a 'jobs' column - seems like this is meant to be accounts

**Comment by hkershaw-brown** [comment]
Paul Hall has edited this (can close issue when it is pushed to the website)

**Comment by hkershaw-brown** [comment]
Comment from new faculty that this rates page is confusing.

Group premium unclear
Storage costs are not in the table (only home directory is in the table)
'per account' is confusion, e.g. group premium is the account so the table is unclear that the limits are per user 

'total running job wallclock of 998,400 core-minutes' does not make sense.  Wallclock is not measured in core-minutes

**Comment by paulstey** [comment]
I've fixed the "wallclock of 998,400 core-minutes" issue. 

I'm also inclined to agree that "per account" is a bit confusing in the context of group premium. @hkershaw-brown : do you have a recommended change?

**Comment by paulstey** [comment]
I've changed the table headings to make things a bit more clear. We can re-open this issue if necessary.
