### ISSUE TITLE
How to cite CCV is missing 

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#53]
Here is the text from the old website:

**Acknowledgment**
If you publish research that benefited from the use of CCV services or resources, we would greatly appreciate an acknowledgment that states:

This research [Part of this research] was conducted using [computational/visualization]
resources and services at the Center for Computation and Visualization, Brown University.

**Facilities Statement**
If you are writing a grant proposal for research that will use CCV facilities, please use the following text as a short description of our facilities:

Brown University continues to make significant investments in resources to promote high performance computing, analysis, and handling of massive data sets. A key resource is the Center for Computation and Visualization (CCV). CCV functions are to partner with faculty and researchers in their funded research projects with CCV application scientists, who write, test, and optimize code, and are co-authors on scientific publications; to generate, store, backup, analyze or visualize large datasets; and to provide the necessary infrastructure, including support, to transfer and share data at high bandwidths through a parallel file system. CCV establishes collaborations with research groups to install, run, test, and debug parallel or compute-intensive algorithms and applications and provides access to systems with specialized hardware, such as large memories or GPU co accelerators. CCV also provides a business model to integrate externally funded hardware into Brown’s on-campus data center.

The computing platform comprises a 450+ high performance computing node system, some with extra large memory and some with GPUs for accelerated computing, for a total core count of over 7,000, and peak performance of roughly 125 Teraflops. A GPFS parallel filesystem provides roughly 400 Terabytes of disk storage and 40 Gigabits per second Infiniband connectivity is used for all parallel applications messaging and I/O. The storage system is integrated with a 2 Petabyte Tivoli TSM backup/archival system. CCV also maintains a high end visualization lab with large scale immersive visualization capabilities. This includes a fully immersive 360 degree YURT, a 3-wall Cave system, and a multi-projector stereo flat display wall. Custom visualization solutions for software and hardware needs are available.

Please contact us if you need a more detailed description.

**Comment by paulstey** [comment]
It seems like this is fixed now, right @fernandogelin?
