### ISSUE TITLE
add google custom search

### ISSUE THREAD

**Issue by hkershaw-brown** [brown-ccv/ccv-website-hugo#54]
The search on the main website does not return results from the documentation (gitbook) pages

**Comment by fernandogelin** [comment]
@hkershaw-brown the ccv site is static and the search uses the the index created from the content files. The documentation is a separate service. Something to keep in mind is to set up an elastic search to include GitBook and Medium. However this is probably time consuming and not a priority at the moment.

**Comment by paulstey** [comment]
@fernandogelin: Do you think we could put someone from our CCV Intern Team on this? I like your idea about setting up elastic search for GitBook and Medium—that would be awesome!

**Comment by fernandogelin** [comment]
fix in branch `feature-gcs`
