### ISSUE TITLE
Calendar page

### ISSUE THREAD

**Issue by phall-brown** [brown-ccv/ccv-website-hugo#67]
I have gotten feedback from Oscar users that using the "Upcoming Events" feature on the home page to find out about upcoming events can be not obvious and/or cumbersome. Would it be possible to set up a simple calendar page where events can be viewed one month at a time? For example, something like [this](https://events.brown.edu/biomed/view/all).

**Comment by phall-brown** [comment]
CCV now has a working calendar at [events.brown.edu](https://events.brown.edu/ccv). Could we add a link to this calendar to the main menu on the CCV website (i.e., along with About, Services, Documentation, New)? I suggest linking to either the month view of upcoming events, which gives a  regular calendar layout for the current month ([https://events.brown.edu/ccv/view/month](https://events.brown.edu/ccv/view/month)) or to the list of all upcoming CCV events ([https://events.brown.edu/ccv/view/all](https://events.brown.edu/ccv/view/all)). Thanks!

**Comment by fernandogelin** [comment]
@Rashi1997 Can you take a look at this?
Also, maybe think of a better way to display the upcoming events in the home page? Currently it creates daily cards but it doesn't have a calendar view.

**Comment by phall-brown** [comment]
Might be possible to somehow just use/appropriate the calendar view from events ([https://events.brown.edu/ccv/view/month](https://events.brown.edu/ccv/view/month))?

**Comment by fernandogelin** [comment]
addressed in ba0d681ef5f86b14b295e1254816d438877558e6
