### ISSUE TITLE
missing link to Oscar documentation

### ISSUE THREAD

**Issue by phall-brown** [brown-ccv/ccv-website-hugo#74]
The link to documentation within the Oscar box on https://ccv.brown.edu/services/ seems to have disappeared.

**Comment by paulstey** [comment]
Has this been fixed? I see the link now.

<img width="629" alt="Screen Shot 2019-10-20 at 3 45 50 PM" src="https://user-images.githubusercontent.com/6303310/67165242-c9cb7c00-f350-11e9-902b-f6b18bdae791.png">
