### ISSUE TITLE
Link to CCV GitHub

### ISSUE THREAD

**Issue by paulstey** [brown-ccv/ccv-website-hugo#78]
Could we add a link to our CCV GitHub? I think we probably want to feature it prominently somewhere, since it's our collective work product. 

We should probably also include a link to the CBC GitHub, too. And are there others?

I'm not sure where we want these to go, but I just wanted to raise this for discussion.

**Comment by fernandogelin** [comment]
hello @TiffL can you add the github links to the footer? there's a fontawesome icon for github.

**Comment by fernandogelin** [comment]
thanks @TiffL
