### ISSUE TITLE
script to get `ready.yml` only scans 100 repos

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-hugo#79]
@TiffL I think I figured out why the script wasn't working for `brown-ccv`. The GitHub API only allows a max of 100 in the `per_page` parameter. 
Can you look into pagination and update the script to take that into account?
Here's some useful information: https://developer.github.com/v3/guides/traversing-with-pagination/#

**Comment by fernandogelin** [comment]
@TiffL have you had a chance to look into this?

**Comment by TiffL** [comment]
@fernandogelin Yes, currently working on it.

**Comment by fernandogelin** [comment]
@TiffL 👩‍💻

**Comment by fernandogelin** [comment]
completed. need to merge.
