### ISSUE TITLE
add list of publications

### ISSUE THREAD

**Issue by fernandogelin** [brown-ccv/ccv-website-hugo#9]
- add filterable list of publications
- get DOI from all publications, or create a database.

**Comment by fernandogelin** [comment]
@mauradriscoll is working on this!

**Comment by mcmcgrath13** [comment]
A first draft is complete and at ccv.brown.edu/pubs

Still to do:
- [ ] way to add pubs (API post route, front end would be nice)
- [ ] make viz more interactive
- [ ] loading time is kind of slow - speed this up

**Comment by fernandogelin** [comment]
closing this as publications is it's own app. all issues related to it should go to the ccv pubs repo.
